spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_management # URL базы данных
    username: root # имя пользователя базы данных
    password: 1337 # пароль к базе
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update # Автоматическое создание таблиц
    show-sql: true # Показывать SQL-запросы в логах

  logging:
    level:
      #org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicTypeDescriptor: TRACE
server:
  port: 8081